version: '3.7'
services:
  database:
    image: postgres
    container_name: rentalx_db
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: rentalx
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
